# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - aix
      - darwin
      - freebsd
      - illumos
      - linux
      - netbsd
      - openbsd
      - plan9
      - solaris
      - windows
    main: ./uncork.go
 # archives:
 #  - replacements:
 #      darwin: Darwin
 #      linux: Linux
 #      windows: Windows
 #      386: i386
 #      amd64: x86_64
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
